### ISSUE TITLE
テストコード導入

### ISSUE THREAD

**Issue by noid11** [itooww/cloudwatch-logs-cleaner#1]
導入したい。

参考になりそうなサイト

Testable Lambda: Working Effectively with Legacy Lambda - Speaker Deck
https://speakerdeck.com/twada/testable-lambda-working-effectively-with-legacy-lambda

外部に依存したコードもテストで駆動する / Test-Driven Architecture - AWS Dev Day Tokyo 2018 - Speaker Deck
https://speakerdeck.com/twada/test-driven-architecture-aws-dev-day-tokyo-2018

localstack も気になったが、 moto というのが手軽そう。

spulec/moto: A library that allows you to easily mock out tests based on AWS infrastructure.
https://github.com/spulec/moto

boto3からDynamoDBへのアクセスをmotoでモックしてみる ｜ DevelopersIO
https://dev.classmethod.jp/server-side/python/moto-dynamodb/

**Comment by noid11** [comment]
テストコード実行
```bash
python -m pytest tests/ -v
```

**Comment by noid11** [comment]
localstack は docker compose で動かせること確認

docker-compose.yaml
```yaml
version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - 4567-4597:4567-4597
      - 8080:8080
```

実行
```bash
docker-compose up -d
```

停止
```bash
docker-compose down
```
